### ISSUE TITLE
## Ticket: Configure Next.js Routes with Nested and Dynamic Routing

### ISSUE THREAD

**Issue by mutaremalcolm** [mutaremalcolm/inception_ai#2]
### Description
Configure Next.js routing to handle nested and dynamic routes for the Khan Board project. This includes setting up both static and dynamic routes to ensure a well-structured navigation system.

### Tasks
- [ ] **Set Up Basic Routing**:
  - Create the basic page structure in the `pages` folder for static routes (e.g., `index.js`, `about.js`, `contact.js`).

- [ ] **Configure Nested Routes**:
  - Create nested folders inside the `pages` directory to manage nested routes.
  - Example structure:
    ```
    /pages
      /dashboard
        index.js
        settings.js
      /profile
        [username].js
    ```

- [ ] **Implement Dynamic Routing**:
  - Set up dynamic routes using file-based routing.
  - For example, create a file `[id].js` inside a folder to handle dynamic paths:
    ```
    /pages
      /posts
        [id].js
    ```
  - Handle the dynamic parameter in the component:
    ```jsx
    import { useRouter } from 'next/router';

    const Post = () => {
      const router = useRouter();
      const { id } = router.query;

      return <div>Post ID: {id}</div>;
    };

    export default Post;
    ```

- [ ] **Add Catch-All Routes**:
  - Implement catch-all routes to handle undefined paths:
    ```
    /pages
      [...slug].js
    ```

- [ ] **Update Navigation Components**:
  - Ensure navigation components (e.g., menu, links) are updated to use the new routes.
  - Verify that the links are correctly pointing to the new routes.

- [ ] **Test Routing Functionality**:
  - Test all routes to ensure they work as expected, including nested and dynamic routes.
  - Validate that navigation is functioning properly and that all dynamic parameters are correctly handled.

### Acceptance Criteria
- The routing should be correctly configured for both static and dynamic routes.
- Nested routes should be properly structured and accessible.
- Catch-all routes should handle undefined paths gracefully.
- Navigation components should be updated to reflect the new routes.
- Routing functionality should be tested and verified for correctness.

**Comment by mutaremalcolm** [comment]
After stand up meeting with Authenticator. Resolved t rescaffold project to better meet project requirements.
