### ISSUE TITLE
# Epic: Video Generation AI (Replicate AI)

### ISSUE THREAD

**Issue by mutaremalcolm** [mutaremalcolm/inception_ai#20]
## Story: Implement Video Generation using Replicate AI

- **Task**: Set up the UI for video generation
  - [x] Create a form for users to input video generation requests.
  - [x] Style the video generation form using Tailwind CSS.

- **Task**: Integrate with Replicate AI’s video generation API
  - [x] Implement the API call to Replicate AI’s video service.
  - [x] Display the generated video or a download link.

**Comment by mutaremalcolm** [comment]
There is an inaccuracy on the output received from the API call for the Video Generation model. The videos are not accurately matching the text prompt given. A new ticket  has been created to investigate and resolve the issue. At this point it is necessary to proceed without exceeding the limited API calls from Replicate.
