### ISSUE TITLE
# Epic: API Limit

### ISSUE THREAD

**Issue by mutaremalcolm** [mutaremalcolm/inception_ai#22]
## Story: Set Up API Limit for Users

- **Task**: Add server-side logic to limit API usage per user
  - [x] Set up API usage tracking in the database.
  - [x] Implement logic to check and enforce API limits.

- **Task**: Store API usage information in the database
  - [x] Create a model in Prisma to store user API usage data.
  - [x] Update the model each time an API request is made.

**Comment by mutaremalcolm** [comment]
A blocking issue was encountered in relation to the implementation of a database through Prisma and PlanetScale. PlanetScale no-longer  provide a free-tier. After a stand-up conversation with Jason Damon, it was resolved to implement Neon as a solution although MongoDb was also strongly considered.
