### ISSUE TITLE
# Epic: Deployment & Wrap Up

### ISSUE THREAD

**Issue by mutaremalcolm** [mutaremalcolm/inception_ai#32]
## Story: Deploy Application

- **Task**: Deploy the application to Vercel
  - [x] Set up the Vercel project.
  - [x] Deploy the Next.js app.

- **Task**: Set up environment variables for production
  - [x] Add production environment variables to Vercel.
